import {
  AUTHORING_TILE_SIZE,
  AUTOMAP_DIR,
  AUTOMAP_RULES_FILE,
  floorTilesetReference,
  TERRAIN_BLOCKING_TILE_ID,
  wallTilesetReference,
} from "@/src/map/authoring/catalog.ts";
import type { TiledMap } from "@/src/map/authoring/tiled_types.ts";
import { jsonSource, property } from "./json_utils.ts";

export function generatedAutomappingSources(): Readonly<Record<string, string>> {
  return {
    [AUTOMAP_RULES_FILE]: [
      "# Generated by deno task maps:sync-authoring",
      "reset_walls.tiled.json",
      "wall_variants.tiled.json",
      "",
    ].join("\n"),
    [`${AUTOMAP_DIR}/reset_walls.tiled.json`]: jsonSource(resetWallsAutomapRuleMap()),
    [`${AUTOMAP_DIR}/wall_variants.tiled.json`]: jsonSource(wallVariantsAutomapRuleMap()),
  };
}

function resetWallsAutomapRuleMap(): TiledMap {
  const width = 7;
  const height = 1;
  const baseWall = terrainGid(TERRAIN_BLOCKING_TILE_ID);
  const input = emptyTileData(width, height);
  const output = emptyTileData(width, height);
  for (
    const [x, terrainId] of [
      [0, TERRAIN_BLOCKING_TILE_ID],
      [2, TERRAIN_BLOCKING_TILE_ID + 1],
      [4, TERRAIN_BLOCKING_TILE_ID + 2],
    ] as const
  ) {
    input[x] = terrainGid(terrainId);
    output[x] = baseWall;
  }
  return automapRuleMap(width, height, [
    tileLayer(1, "input_terrain", width, height, input),
    tileLayer(2, "output_terrain", width, height, output),
  ]);
}

function wallVariantsAutomapRuleMap(): TiledMap {
  const width = 7;
  const height = 3;
  const wall = terrainGid(TERRAIN_BLOCKING_TILE_ID);
  const input = emptyTileData(width, height);
  const output = emptyTileData(width, height);

  setTile(input, width, 0, 1, wall);
  setTile(input, width, 1, 1, wall);
  setTile(input, width, 2, 1, wall);
  setTile(output, width, 1, 1, terrainGid(TERRAIN_BLOCKING_TILE_ID + 1));

  setTile(input, width, 5, 0, wall);
  setTile(input, width, 5, 1, wall);
  setTile(input, width, 5, 2, wall);
  setTile(output, width, 5, 1, terrainGid(TERRAIN_BLOCKING_TILE_ID + 2));

  return automapRuleMap(width, height, [
    tileLayer(1, "input_terrain", width, height, input),
    tileLayer(2, "output_terrain", width, height, output),
  ]);
}

function automapRuleMap(width: number, height: number, layers: TiledMap["layers"]): TiledMap {
  return {
    compressionlevel: -1,
    height,
    infinite: false,
    layers,
    nextlayerid: layers.length + 1,
    nextobjectid: 1,
    orientation: "orthogonal",
    properties: [
      property("AutomappingRadius", 1),
      property("MatchInOrder", true),
    ],
    renderorder: "right-down",
    tiledversion: "1.12.2",
    tileheight: AUTHORING_TILE_SIZE,
    tilesets: [automapFloorTilesetReference(), automapWallTilesetReference()],
    tilewidth: AUTHORING_TILE_SIZE,
    type: "map",
    version: "1.10",
    width,
  };
}

function tileLayer(
  id: number,
  name: string,
  width: number,
  height: number,
  data: readonly number[],
): TiledMap["layers"][number] {
  return {
    data,
    height,
    id,
    name,
    opacity: 1,
    type: "tilelayer",
    visible: true,
    width,
    x: 0,
    y: 0,
  };
}

function emptyTileData(width: number, height: number): number[] {
  return Array.from({ length: width * height }, () => 0);
}

function setTile(data: number[], width: number, x: number, y: number, gid: number): void {
  data[y * width + x] = gid;
}

function terrainGid(terrainId: number): number {
  return terrainId + 1;
}

function automapFloorTilesetReference(): ReturnType<typeof floorTilesetReference> {
  return {
    ...floorTilesetReference(),
    source: `../${floorTilesetReference().source}`,
  };
}

function automapWallTilesetReference(): ReturnType<typeof wallTilesetReference> {
  return {
    ...wallTilesetReference(),
    source: `../${wallTilesetReference().source}`,
  };
}
