import {
  AUTOMAP_DIR,
  COMPILED_MAPS_PATH,
  ENTITY_MARKERS_IMAGE,
  ENTITY_MARKERS_TILESET,
  MAPS_DIR,
  TEMPLATE_DIR,
  TERRAIN_TILESETS_DIR,
  TILED_PROJECT_PATH,
} from "@/src/map/authoring/catalog.ts";
import { generatedAutomappingSources } from "./automap.ts";
import { generatedCompiledMapsSource } from "./compile.ts";
import { checkGeneratedBytes, checkGeneratedText, readRequiredTextFile } from "./json_utils.ts";
import { generatedEntityMarkersImage, generatedEntityMarkersTilesetSource } from "./markers.ts";
import { generatedTemplateSources } from "./templates.ts";
import { generatedTerrainSources } from "./terrain_atlas.ts";
import { generatedTiledProjectSource } from "./tiled_project.ts";

export async function checkMaps(): Promise<void> {
  const source = await generatedCompiledMapsSource();
  const issues = await generatedAuthoringIssues();

  const existing = await readRequiredTextFile(
    COMPILED_MAPS_PATH,
    `${COMPILED_MAPS_PATH} is missing. Run deno task maps:compile.`,
  );
  if (existing !== source) issues.push(`${COMPILED_MAPS_PATH} is stale. Run deno task maps:compile.`);

  if (issues.length > 0) throw new Error(`Map authoring check failed:\n${issues.join("\n")}`);
}

async function generatedAuthoringIssues(): Promise<string[]> {
  const issues: string[] = [];
  await checkGeneratedText(TILED_PROJECT_PATH, generatedTiledProjectSource(), issues);
  await checkGeneratedText(`${MAPS_DIR}/${ENTITY_MARKERS_TILESET}`, generatedEntityMarkersTilesetSource(), issues);
  await checkGeneratedBytes(`${MAPS_DIR}/${ENTITY_MARKERS_IMAGE}`, generatedEntityMarkersImage(), issues);

  const expectedAutomap = generatedAutomappingSources();
  for (const [path, source] of Object.entries(expectedAutomap)) {
    await checkGeneratedText(path, source, issues);
  }

  const expectedTerrainSources = await generatedTerrainSources();
  for (const [path, source] of Object.entries(expectedTerrainSources)) {
    if (typeof source === "string") {
      await checkGeneratedText(path, source, issues);
    } else {
      await checkGeneratedBytes(path, source, issues);
    }
  }

  const expectedTemplates = generatedTemplateSources();
  for (const [path, source] of Object.entries(expectedTemplates)) {
    await checkGeneratedText(path, source, issues);
  }

  try {
    for await (const entry of Deno.readDir(TEMPLATE_DIR)) {
      if (!entry.isFile || !entry.name.endsWith(".tx")) continue;
      const path = `${TEMPLATE_DIR}/${entry.name}`;
      if (expectedTemplates[path] === undefined) issues.push(`${path} is not generated by the authoring catalog.`);
    }
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      issues.push(`${TEMPLATE_DIR} is missing. Run deno task maps:sync-authoring.`);
    } else {
      throw error;
    }
  }

  try {
    for await (const entry of Deno.readDir(AUTOMAP_DIR)) {
      if (!entry.isFile) continue;
      const path = `${AUTOMAP_DIR}/${entry.name}`;
      if (expectedAutomap[path] === undefined) issues.push(`${path} is not generated by the authoring catalog.`);
    }
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      issues.push(`${AUTOMAP_DIR} is missing. Run deno task maps:sync-authoring.`);
    } else {
      throw error;
    }
  }

  try {
    for await (const entry of Deno.readDir(TERRAIN_TILESETS_DIR)) {
      if (!entry.isFile) continue;
      const path = `${TERRAIN_TILESETS_DIR}/${entry.name}`;
      if (expectedTerrainSources[path] === undefined) issues.push(`${path} is not generated by the authoring catalog.`);
    }
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      issues.push(`${TERRAIN_TILESETS_DIR} is missing. Run deno task maps:sync-authoring.`);
    } else {
      throw error;
    }
  }

  return issues;
}
